apiVersion: v1
kind: Service
metadata:
  name: booking-management-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5002
  selector:
    app: booking-management-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-management-service
  template:
    metadata:
      labels:
        app: booking-management-service
    spec:
      containers:
      - name: booking-management-service
        image: "dlakdocker/booking-management-service:1.1"
        ports:
        - containerPort: 5002
        env:
        - name: NODE_ENV
          value: "qa"
      nodeSelector:
        nodetype: "worker"
