apiVersion: v1
kind: Service
metadata:
  name: envoy-api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: envoy-api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-api-gateway
  template:
    metadata:
      labels:
        app: envoy-api-gateway
    spec:
      containers:
      - name: envoy-api-gateway
        image: "dlakdocker/envoy-api-gateway:latest"
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "pre-prod"
      nodeSelector:
        nodetype: "worker"
