apiVersion: v1
kind: Service
metadata:
  name: host-management-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: host-management-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host-management-service
  template:
    metadata:
      labels:
        app: host-management-service
    spec:
      containers:
      - name: host-management-service
        image: "dlakdocker/host-management-service:latest"
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "pre-prod"
      nodeSelector:
        nodetype: "worker"
