apiVersion: v1
kind: Service
metadata:
  name: notification-management-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5004
  selector:
    app: notification-management-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-management-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-management-server
  template:
    metadata:
      labels:
        app: notification-management-server
    spec:
      containers:
      - name: notification-management-server
        image: "dlakdocker/notification-management-server:latest"
        ports:
        - containerPort: 5004
        env:
        - name: NODE_ENV
          value: "qa"
      nodeSelector:
        nodetype: "worker"
