apiVersion: v1
kind: Service
metadata:
  name: passport
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: passport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passport
  template:
    metadata:
      labels:
        app: passport
    spec:
      containers:
      - name: passport
        image: "dlakdocker/passport:latest"
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "pre-prod"
      nodeSelector:
        nodetype: "worker"
