apiVersion: v1
kind: Service
metadata:
  name: payment-management-service
spec:
  type: ClusterIP
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: payment-management-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-management-service
  template:
    metadata:
      labels:
        app: payment-management-service
    spec:
      containers:
      - name: payment-management-service
        image: "dlakdocker/payment-management-service:latest"
        ports:
        - containerPort: 5003
        env:
        - name: NODE_ENV
          value: "pre-prod"
      nodeSelector:
        nodetype: "worker"
